version: '3.5'
volumes:
  db_data:
  app_data:
services:
  db:
    restart: always
    build:
      context: ../
      dockerfile: docker/postgres/Dockerfile
    image: otorongo/otorongo_db
    volumes:
      - db_data:/srv/postgresql/data/
    expose:
      - '5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    command: postgres
      -c max_connections=1000
  app:
    restart: always
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    image: otorongo/otorongo_app
    command: |
      /wait_for_it.sh db:5432 -t 0 -- gunicorn
      --workers 8
      --timeout 120
      --worker-class aiohttp.worker.GunicornWebWorker
      --log-level debug
      --error-logfile=-
      --preload
      -b 0.0.0.0:8000 otorongo.wsgi
    volumes:
      - app_data:/data
      - /logs
    expose:
      - "8001"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: 'otorongo.settings.production'
  nginx:
    restart: always
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    image: otorongo/otorongo_nginx
    volumes:
      - app_data:/data
    ports:
      - "4083:80"
      - "4433:443"
    depends_on:
      - app
  redis:
    restart: always
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - app_data:/data
    expose:
      - '6379'
